INSERT INTO `events` (`id_event`, `name_event`, `topic`, `begin_year`, `begin_month`, `begin_day`, `end_year`, `end_month`, `end_day`, `description`, `id_period`, `id_location`) VALUES
(3, 'Festival de Natsu', NULL, NULL, 6, 20, NULL, 6, 27, 'Fête célébrant l''été au pays de l''Air, où se réunissent de nombreux marchands pour former le plus grand marché de l''année et du pays. Semblable à une grande foire. On peut trouver de tout venant de partout, c''est l''occasion de faire des affaires et de rencontrer des voyageurs. De grands jeux et concours de toutes sortes sont organisés pendant quelques jours. ', 2, 12),
(4, 'Festival du Feu', NULL, NULL, 9, 20, NULL, 9, 27, 'Fête en l''honneur d''Entei. La capitale du pays du Feu accueille pendant quelques jours l''un de ses Pokémon emblèmes, afin qu''il bénisse les jeunes maîtres du Feu nés dans l''année et les bébés Pokémon du même type. Musiques entraînantes résonnent dans la cité, les costumes aux couleurs chaudes et brillantes sont de sortie. La fête dure deux jours et se poursuit dans la nuit.', 2, 13),
(5, 'Festival d''Hiver', NULL, NULL, 12, 20, NULL, 12, 27, 'Fête célébrant l''Hiver. Un grand défilé y est organisé ainsi que de nombreuses festivités. On peut trouver des vendeurs de costumes pour tous les goûts, toutes les tailles, et même pour les Pokémon. Ce Festival dure sept jours, au terme desquels Suicune apparaît s''il le juge réussi, symbole de chance et de bénédiction pour les maîtres de l''Eau.', 2, 14),
(6, 'Halloween', NULL, NULL, 10, 30, NULL, 11, 1, 'Fête traditionnelle dans laquelle on joue à se faire peur le temps d''une soirée. Diverses cérémonies sont organisées, on peut trouver partout de quoi s''amuser. ', 2, 1),
(7, 'Festival du Printemps', NULL, NULL, 3, 20, NULL, 3, 27, 'Fête célébrant le renouveau des saisons et de la vie au Printemps. Alors que les arbres bourgeonnent, les habitants décorent leurs villes de jeunes fleurs et Raikou visite la capitale de la Terre afin d''y bénir les amoureux et l''amour en général (familial, amical, de dresseur à Pokémon) en leur offrant des bouquets de fleurs. On dit que si les cerisiers sont en fleurs ce jour-là, un amour déclaré sous l''un d''eux sera éternel. ', 2, 15),
(8, 'Fête de la Lune – Saint Valentin', NULL, NULL, 2, 10, NULL, 2, 15, 'La Ville Lunaire est toujours en pleine effervescence, mais dans cette période particulière, la légende raconte que le croissant de Lune rose qui apparaît tous les ans serait en fait Cresselia dormant au milieu des étoiles. Profitant de ce mythe, les habitants de la ville organisent une grande fête d''une nuit en son honneur, en particulier pour les amoureux.', 2, 16),
(9, 'Rite de la paix', NULL, NULL, 12, 31, NULL, 12, 31, NULL, 2, 7),
(10, 'Rite de la Paix', NULL, NULL, 1, 1, NULL, 1, 1, NULL, 2, 7),
(11, 'Foire Marchande', NULL, NULL, 8, 24, NULL, 8, 31, 'Durant cette période, tous les marchands de Tenkei et d''Erasia sont conviés à la cité du Feu, afin de faire l''étalage de leurs produits. Que ce soit des armes, de la nourriture, des vêtements, des bijoux, ... Si vous cherchez quelque chose de particulier, il n''y a pas à douter que c''est ici que vous le trouverez !', 2, 9),
(12, 'Jours des Héros', NULL, NULL, 5, 1, NULL, 5, 4, 'Les habitants de Tenkei commémorent la bravoure des Héros s''étant sacrifiés lors de leur combat contre le Monstre. De nombreux spectacles ont lieu à travers les rues des cités, reprenant les grands événements de cet affrontement. Les festivités s''achèvent par une grande procession jusqu''au Sanctuaire des Tribus respectives, où la population fait une dernière prière collective.', 2, 19),
(13, 'Fête de la Fertilité', NULL, NULL, 3, 17, NULL, 3, 22, 'Équivalent midgardien de la Fête de la Lune et du Festival du Printemps. Les rues sont décorées avec des fleurs d''hiver et les habitants s''offrent les premières fleurs du printemps, tandis qu''une couronne de fleurs est posée sur les enfants nés de l''année passée. La Fête s''achève par un grand feu de joie, où l''on brûle toutes les coiffes de fleurs pour que Démétéros bénisse les enfants et la terre. Qui plus est, on dit qu''un couple jetant un collier de fleurs tissé ensemble dans le brasier verra son amour durer éternellement.', 2, 7),
(14, 'Jour de l''Aigle', NULL, NULL, 11, 11, NULL, 11, 13, 'Jour où les guerriers d''Aliphyr ayant complété leur formation à Linaëwen et réussi l''Épreuve de la Caverne obtiennent le rang de Chevaliers Ailés. Après une fête au sein de l''Académie Militaire de Linaëwen, un grand banquet est organisé au sein de la cité de l''Air, précédé par une cérémonie où le chef d''Aliphyr lui-même remet une plume aux nouveaux adoubés.', 2, 20),
(15, 'Sublimation', NULL, NULL, 1, 9, NULL, 1, 12, 'Deux fois par an, la sérénité d''Abyan se voit fortement chamboulée par cette fête. On se déguise, on chante, on mange, on danse... Tout ou presque est permis au sein de la cité pendant ces quelques jours, pour pallier le manque d''agitation habituel !', 2, 10),
(16, 'Sublimation', NULL, NULL, 7, 9, NULL, 7, 12, 'Deux fois par an, la sérénité d''Abyan se voit fortement chamboulée par cette fête. On se déguise, on chante, on mange, on danse... Tout ou presque est permis au sein de la cité pendant ces quelques jours, pour pallier le manque d''agitation habituel !', 2, 10),
(18, 'Danse des Lumières', NULL, NULL, 8, 1, NULL, 8, 7, 'Appelé « Hikari no Mai » dans la langue de Mizuhan, ce festival dédié aux défunts est un événement majeur dans la vie des habitants de la Nouvelle-Gilnéas. De grandes processions sont organisées un peu partout, pendant lesquelles chacun marche en tenant une lanterne symbolisant l''âme d''un disparu. Des veillées se tiennent également dans le village, au cours desquelles on prie tous ensemble pour le repos des victimes de la folie de Mewtwo et des Méga-Pokémon.', 2, 21),
(19, 'Carnaval', 'http://erasia-rpg.forum-actif.net/t3347-carnaval', 2016, 3, 20, 2016, 6, 26, 'Partout sur Érasia et Midgard, les premiers vents chauds réchauffent les cœurs et rassurent les habitants. L''hiver s''en va, laissant enfin sa place à la vie sous toutes ses incarnations. Les humains et les Pokémon sont heureux, et c''est l''occasion d''organiser la fête du Carnaval qui, selon les régions, se manifeste sous des formes très différentes...', 1, 1),
(20, 'Course', 'http://erasia-rpg.forum-actif.net/t3534-course-pokemon', 2016, 10, 9, 2016, 12, 31, 'Partout sur Érasia et Midgard, les gens se préparent à affronter l''hiver qui arrive. Mais au milieu des préparatifs, certains organisent des petites festivités pour se détendre avant de reprendre le dur labeur. À la Mélopée de la Nymphe, au Grand Large et dans les Cieux, des Courses de Pokémon proposent aux Dresseurs du monde entier de mettre à l''épreuve la vitesse de leurs animaux. Au même moment, un Concours se monte au Cosmo Canyon, où seuls les plus futés pourront tenter de décrocher un ruban.', 1, 1);

INSERT INTO `locations` (`id_location`, `name_location`) VALUES
(1, 'Partout dans le monde...'),
(2, 'Érasia'),
(3, 'Terros'),
(4, 'Mizuhan'),
(5, 'Flamen'),
(6, 'Nalcia'),
(7, 'Tenkei / Midgard'),
(8, 'Aliphyr'),
(9, 'Torcan'),
(10, 'Abyan'),
(11, 'Dyrinn'),
(12, 'Nalcia - Eternara'),
(13, 'Flamen - Omatsu'),
(14, 'Mizuhan - Cité Arkan'),
(15, 'Terros - Cité de Seian'),
(16, 'Terros - Ville Lunaire'),
(19, 'Tenkei / Midgard - Abyan, Aliphyr, Torcan & Dyrinn'),
(20, 'Aliphyr & Linaëwen'),
(21, 'Mizuhan - Nouvelle-Gilnéas'),
(22, 'Tenkei / Midgard - Place d''Ivoire');